### ISSUE TITLE
Why when inject a game that use directx 11 i'm getting exception in the Capture project ?

### ISSUE THREAD

**Issue by Csharper1972** [spazzarama/Direct3DHook#24]

**Comment by Csharper1972** [comment]
I found the solution just copied the dll file to all the places in both projects TestScreenshot and Capture and now it's working.

**Comment by Csharper1972** [comment]
Any game that auto detect as directx 11 i'm getting this exception: 

System.IndexOutOfRangeException was caught
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=Capture
  StackTrace:
       at Capture.Hook.DX11.DXFont.GetCharRect(Char c) in c:\Temp\hook\Direct3DHook-master\Capture\Hook\DX11\DXFont.cs:line 251
       at Capture.Hook.DX11.DXSprite.DrawString(Int32 X, Int32 Y, String text, Int32 R, Int32 G, Int32 B, Int32 A, DXFont F) in c:\Temp\hook\Direct3DHook-master\Capture\Hook\DX11\DXSprite.cs:line 258
       at Capture.Hook.DX11.DXOverlayEngine.Draw() in c:\Temp\hook\Direct3DHook-master\Capture\Hook\DX11\DXOverlayEngine.cs:line 145
       at Capture.Hook.DXHookD3D11.PresentHook(IntPtr swapChainPtr, Int32 syncInterval, PresentFlags flags) in c:\Temp\hook\Direct3DHook-master\Capture\Hook\DXHookD3D11.cs:line 384
  InnerException: 


I didn't change anything but still every game that use directx 11 give this exception.

**Comment by spazzarama** [comment]
Sounds like it is trying to draw a character that it hasn't prepared...

**Comment by Csharper1972** [comment]
Strange, not my character since i didn't change anything or added anything.
If you a solution for that a code with a solution please inform me. Thank you.

**Comment by spazzarama** [comment]
I suggest you attach the debugger to the target, and then run your host to
inject the assembly.

You should get a break on the exception, or otherwise work on getting a
breakpoint in there.

I haven't personally had this exception happen, but it sounds like it is
trying to find the character (whatever it is) and isn't finding it. This
could be an issue with locale or anything, I don't know, depends what is
trying to render text.

Regards,
Justin

**Comment by spazzarama** [comment]
Duplicate #26
