### ISSUE TITLE
 Error in InitialiseHook: System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.

### ISSUE THREAD

**Issue by dieuhue1710** [spazzarama/Direct3DHook#70]
Whe trying hook game with Dx11 and Dx9. I using on CPU AMD Ryzen 5 2400G (Work fine with Core i3 4160)

Information: Disconnecting from process 15316
Error: Error in InitialiseHook: System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at SharpDX.Desktop.Properties.Resources.get_ResourceManager()
   at SharpDX.Desktop.Properties.Resources.get_logo()
   at SharpDX.Windows.RenderForm..ctor(String text)
   at Capture.Hook.DXHookD3D11.Hook() in C:\Users\Felix\Downloads\Direct3DHook-master\Direct3DHook-master\Capture\Hook\DXHookD3D11.cs:line 130
   at Capture.EntryPoint.InitialiseDirectXHook(CaptureConfig config) in C:\Users\Felix\Downloads\Direct3DHook-master\Direct3DHook-master\Capture\EntryPoint.cs:line 245

**Comment by spazzarama** [comment]
@dieuhue1710 that error is happening within the SharpDX library. You could check if there is an updated library version that works fine.

Alternatively, that logic can be replaced with anything that creates a window handle that can be used for initialising a Direct3D device.
